### PR TITLE
Add autoclosing command

### PR DESCRIPTION
**Pull request by grimmlink**
Hi,

Sorry it took time, I've been quite busy but i managed to work on it today.
So, I made a command with an argument (to choose the username of the updater) and an option to filter the resolved tickets by age.

I don't quite understand why in your command you look for a user 'system'

```
               ->setUser($userManager->findUserByUsername('system'))
```
https://github.com/hackzilla/TicketBundle/blob/master/Command/TicketManagerCommand.php#L59

### CODE REVIEW

**Comment by grimmlink** [comment]
See : https://github.com/hackzilla/TicketBundle/issues/26

**Comment by grimmlink** [comment]
added a little template modification, i got tired of deleting tickets by clicking on the wrong button...

**Comment by hackzilla** [comment]
```
->setUser($userManager->findUserByUsername('system'))
```
Is because tickets need to be owned by someone, but isn't documented anywhere.

I'm not entirely happy how users work in this bundle, and it needs some work.

**Comment by hackzilla** [comment]
I've tagged up to your PR as 0.9.1.

I have reworked it the command slightly to make it more efficient, and it's currently in master.
It works for me, but can you double check it still works as you expected?

/ping @grimmlink

**Comment by grimmlink** [comment]
Hey,

Sorry for the absence, had a new project to work on and got quite busy.
I will test it later and let you know !

**Pull request merged**
